apiVersion: v1
kind: Config
current-context: kube-admin@kube-playground # This is used to set a default context to use to let K8s know which to login with
clusters: # Multiple clusters can be added
- name: kube-playground
  cluster:
    certificate-authority: ca.crt # In here, you can specify the full path to the certificate
    # certificate-authority-data: This can also be used instead of the above and you include th base64 verison
    server: https://kube-playground:6443 # This could also be ip address of the K8s

contexts: # Multiple contexts can be added
- name: kube-admin@kube-playground
  context:
    cluster: kube-playground
    user: kube-admin
    namespace: default

users: # Multiple users can be added
- name: kube-admin
  user:
    client-certificate: admin.crt
    client-key: admin.key