apiVersion: v1 # This is the api version of the object to be created 
kind: Pod # This specifies the type of object to be created 
metadata:
  name: myapp-pod # This is the name given to the Pod
spec: # This defines whats in the object we are creating
  containers:
    - name: nginx-container # nginx-container is the name of the image in Docker repository
      image: nginx
  toleration:
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"