apiVersion: v1
kind: ReplicationController
metadata:
    name: myapp-rc
    lables:
      name: myapp
      type: front-end
spec:
    replicas: 3
    
    template:
      metadata:
        name: 
        labels:
          app: hello-world
      spec:
        containers:
        -   name: nginx-container
            image: nginx